### PR TITLE
added Range and Scale settings

### PR DESCRIPTION
**Pull request by stefan0uh**

### CODE REVIEW

**Comment by stefan0uh** [comment]
Only tested on Classic and maybe a switch to the default in-range check should be added cause, not everyone wants a 30yards range check

**Comment by brittyazel** [comment]
I pulled in only part of this patch, namely the part allowing to change the frame scale.

I'm not in love with the way the range indication was implemented, mainly because it was confusing and potentially breaking. Setting the range indication based on a single spell is an interesting way about going about it, I'm not sure if it's the best approach though. In the past we could query our distance from a player directly, and that was ideal, but they removed that unfortunately.

My main concerns are #1, this is a confusing option for players, #2 this will cause potential breakage (I always worry about this when we override built in functionality.)

**Comment by stefan0uh** [comment]
> I'm not in love with the way the range indication was implemented, mainly because it was confusing and potentially breaking. Setting the range indication based on a single spell is an interesting way about going about it, I'm not sure if it's the best approach though. In the past we could query our distance from a player directly, and that was ideal, but they removed that unfortunately.

I know, was hoping for a better solution but that's the best I found. (for CLASSIC)

> My main concerns are #1, this is a confusing option for players, #2 this will cause potential breakage (I always worry about this when we override built-in functionality.)

mhh, what do you mean with "potential breaking", I run this "code" couple of weeks and saw no errors except the error with combat leaves.

But that's, why I said a custom option to "opt-in", is needed cause most players are not needing a custom range. Healers normally have 40 yards and descursing needs 30 yards in classic - that's why the custom range was added. (i think its a small use case, but mages are fucked if they casting at max range 36yards and want start decursing which is 30 yards) 

But if you want to add the alpha, you need to do it anyways.  You can do it with `IsSpellInRange` or `UnitInRange`.

```
function EnhancedRaidFrames:UpdateRangeAlpha(frame)
	if string.match(frame.unit, "party") or string.match(frame.unit, "raid") then
		if IsSpellInRange(EnhancedRaidFrames.db.profile.range.spell, frame.displayedUnit) then
			frame:SetAlpha(EnhancedRaidFrames.db.profile.range.alpha.maximum)
			frame.background:SetAlpha(EnhancedRaidFrames.db.profile.range.background.maximum)
		else
			frame:SetAlpha(EnhancedRaidFrames.db.profile.range.alpha.minimum)
			frame.background:SetAlpha(EnhancedRaidFrames.db.profile.range.background.minimum)
		end
	end
end 
```

the usage of `IsSpellInRange` is incorrect, which may break your testing environment.

[returns - 1 if the target is in range of the spell, 0 if the target is not in range of the spell, nil if the provided arguments were invalid or inapplicable.](https://wow.gamepedia.com/API_IsSpellInRange)

**Comment by brittyazel** [comment]
Ok I cherrypicked in your change to the OutOfRange fade as well. Just tested it and that's working pretty great

**Comment by brittyazel** [comment]
I'll keep looking at this. I want to find a more elegant solution. It seems so heavy handed to set everything to be 30 yards or 40 yards. I really wish there was a per-spell way to do it. bleh.

**Comment by brittyazel** [comment]
What if we did per-indicator range checking? We could shade the indicator red tinted if the spell isn't in range or something to provide the visual indicator. That gets around the all or nothing issue I had above

**Comment by stefan0uh** [comment]
> Ok I cherrypicked in your change to the OutOfRange fade as well. Just tested it and that's working pretty great

great 👍 

> I'll keep looking at this. I want to find a more elegant solution. It seems so heavy handed to set everything to be 30 yards or 40 yards. I really wish there was a per-spell way to do it. bleh.

What do you mean with "per-spell way"? That the range is calculating dynamically based on the latest casted spell or a spell the player selects?

> What if we did per-indicator range checking? We could shade the indicator red tinted if the spell isn't in range or something to provide the visual indicator. That gets around the all or nothing issue I had above

I think this is confusing when the "player" frame indicates the player is in range and a other indicates he isn't. It is like the small dot on the "default" action bar, when a spell is in range or not - what I think no one likes.

Overall I prefer a custom range function, with a UI toggle to enable the feature and a dropdown of default ranges (with ranges like 10, 20, 30, 40) or an input field to be flexible for spell names.

```
function rangeCheck(unit) 
    local db = EnhancedRaidFrames.db.profile
    if(db.customRange) then
        return IsSpellInRange(db.rangeSpell, unit) == 0
    else
        local inRange, checkedRange = UnitInRange(unit);
        return checkedRange and not inRange
    end
end
```

**Comment by stefan0uh** [comment]
https://github.com/brittyazel/RaidFrameIndicators/blob/490bc7d928821f2c0439b817ec0adc302a59040e/EnhancedRaidFrames.lua#L206-L211

is it possible to add `frame.background:SetAlpha(EnhancedRaidFrames.db.profile.rangeAlpha)` as well to get the frame fully transparent?
image

**Comment by brittyazel** [comment]
Yes, I just added this in among other things. Please double check my code if you have a chance. I'd appreciate a second set of eyes.

**Comment by stefan0uh** [comment]
Background alpha change looks good for me.

**Pull request merged**
